import { render } from 'preact';
import { createMeasuredLayout } from './layout';
import { Glyph, Harness, screenText, claimScreen } from './screens';
import type { HarnessMark } from './screens';
export interface Metric { id: string; label: string; value: string; explanation?: string; info?: string; note: { text: string; lead?: string; tone?: string; tail?: string } }
export interface AnalyticsRow { id: string; name: string; harness: string; harnessName: string; harnessTip?: string; mark?: HarnessMark; value: string; href?: string; rank?: number; missing?: string; className?: string }
export interface Chart {
  key: string; heading: string; info?: string; sub?: string; empty?: string; width: number; label: string; role: 'img' | 'group'; left: number; right: number;
  grid: readonly { y: number; label: string }[];
  bins: readonly { key: string; x: number; width: number; claude: number; codex: number; barX: number; barWidth: number; active: boolean; label: string; tip?: string; when: string; value: string }[];
  ago: string; legend: readonly { id: string; label: string; mark?: HarnessMark }[]; missing?: string;
}
export interface Breakdown { heading: string; key: string; rows: readonly { key: string; name: string; count: string; width: number; color?: string; hours: string; cost: string; missing?: string }[] }
export interface ModelBand {
  key: string; heading: string; rows: readonly { key: string; name: string; tip: string; count: string; cells: readonly { text: string; n: number; tip?: string }[] }[];
  width: number; points: readonly { x: number; y: number; label: string; tip: string }[];
}
export interface AnalyticsSnapshot {
  heading: string; error?: string; ready: boolean; query: string; metrics: readonly Metric[]; charts: readonly Chart[];
  measure: string; breakdowns: readonly Breakdown[]; lists: readonly { heading: string; rows: readonly AnalyticsRow[] }[];
  models?: readonly ModelBand[]; modelHeaders: readonly string[]; allowance?: { when: string; windows: readonly { label: string; used: string; reset: string }[] };
}
export interface AnalyticsHost { facets(): HTMLElement; committed(): void; measure(value: string): void; breakdown(group: string, key: string): void; session(id: string): void; slice(key: string): void; model(key: string): void }
const states = new WeakMap<HTMLElement, ReturnType<typeof createMeasuredLayout>>();
const COST_INFO = 'M9 9a3 3 0 1 1 4 2.8c-.7.3-1 .9-1 1.7V14M12 18h.01';
function Info({ text }: { text: string }) { return <span class="cost-info" tabIndex={0} role="img" aria-label={text} data-tip={text}><Glyph path={COST_INFO} className="" /></span>; }
function Row({ row, open, widthClass }: { row: AnalyticsRow; open(): void; widthClass: string }) {
  const content = <><span class="session-name">{screenText(row.name)}</span><span class="hlabel">{row.mark && <Harness mark={row.mark} lead={false} />}<span class={'hname h-' + row.harness} data-tip={row.harnessTip}>{row.harnessName}</span></span><span class="session-value">{screenText(row.value)}</span>{row.rank !== undefined && <span class="row-track"><i class={'row-bar ' + widthClass} /></span>}{row.missing && <span class="no-price">{screenText(row.missing)}</span>}</>;
  const cls = (row.className ?? 'analytics-session') + (row.rank === undefined ? '' : ' ranked' + (/^[\w-]+$/.test(row.harness) ? ' h-' + row.harness : ''));
  return row.href ? row.rank !== undefined ? <a class={cls} href={row.href} onClick={event => { if (event.defaultPrevented || event.button || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey || !event.currentTarget.isConnected) return; event.preventDefault(); open(); }}>{content}</a> : <button class={cls} type="button" onClick={open}>{content}</button> : <div class={cls}>{content}</div>;
}
export function renderAnalyticsScreen(root: HTMLElement, snapshot: AnalyticsSnapshot, host: AnalyticsHost) {
  let layout = states.get(root);
  if (!layout) { layout = createMeasuredLayout(); states.set(root, layout); claimScreen(root, "analytics", () => { layout?.destroy(); states.delete(root); }); }
  layout.reset(); const geometry = layout;
  const width = (value: number) => geometry.className('width', value, '%');
  const facets = host.facets();
  const active = (action: () => void) => { if (root.isConnected) action(); };
  render(<><div class="ph"><h1>Analytics</h1><div class="sub">{screenText(snapshot.heading)}</div></div><div class="session-facet-slot" ref={node => { if (node && facets.parentElement !== node) node.append(facets); }} />{snapshot.error && <p class="empty" role="status">{screenText(snapshot.error)}</p>}{snapshot.ready && <>
    <div class="analytics-metrics" data-analytics-ready="" data-query={snapshot.query}>{snapshot.metrics.map(metric => <div key={metric.id} class="analytics-metric" data-more={metric.explanation ? '' : undefined} data-tip={metric.explanation} tabIndex={metric.explanation ? 0 : undefined} aria-describedby={metric.explanation ? metric.id : undefined}>{metric.explanation && <span hidden id={metric.id}>{metric.explanation}</span>}<div class="label"><span>{metric.label}</span>{metric.info && <Info text={metric.info} />}</div><div class="value">{screenText(metric.value)}</div><div class="note">{metric.note.lead ? <span class={metric.note.tone}>{screenText(metric.note.lead)}</span> : null}{screenText(metric.note.text)}{metric.note.tail}</div></div>)}</div>
    {snapshot.charts.map(chart => <section key={chart.key} class="analytics-panel"><h2>{chart.heading}{chart.info && <Info text={chart.info} />}</h2>{chart.empty ? <p class="empty">{chart.empty}</p> : <>{chart.sub && <div class="panel-sub">{screenText(chart.sub)}</div>}<div class="analytics-chart"><svg viewBox={'0 0 ' + chart.width + ' 190'} role={chart.role} aria-label={chart.label}>{chart.grid.map((line, i) => <><line key={'line' + i} x1={chart.left} x2={chart.right} y1={line.y} y2={line.y} class="gridline" /><text key={'label' + i} x={0} y={line.y + 4} class="axis-label">{line.label}</text></>)}{chart.bins.map(bin => <>{bin.claude > 0 && <rect key={'claude' + bin.key} x={bin.barX} y={151 - bin.claude} width={bin.barWidth} height={bin.claude} class="cost-claude" />}{bin.codex > 0 && <rect key={'codex' + bin.key} x={bin.barX} y={151 - bin.claude - bin.codex} width={bin.barWidth} height={bin.codex} class="cost-codex" />}<rect key={'hit' + bin.key} x={bin.x} y={12} width={bin.width} height={139} class="chart-hit" data-tip={bin.tip} role={bin.active ? 'button' : undefined} tabIndex={bin.active ? 0 : undefined} aria-label={bin.active ? bin.label : undefined} onClick={() => { if (bin.active) active(() => host.slice(bin.key)); }} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); if (bin.active) active(() => host.slice(bin.key)); } }} /></>)}<text x={chart.left} y={178} class="axis-label">{chart.ago}</text><text x={chart.right} y={178} text-anchor="end" class="axis-label">Now</text></svg></div><div class="analytics-legend">{chart.legend.map(item => <span key={item.id}><i class={'legend-' + item.id} />{item.mark && <Harness mark={item.mark} lead={false} />}{item.label}</span>)}</div>{chart.bins.some(bin => bin.active) && <details class="chart-slices"><summary>Explore time slices</summary><div class="chart-slice-list">{chart.bins.filter(bin => bin.active).map(bin => <button key={bin.key} class="chart-slice" type="button" onClick={() => active(() => host.slice(bin.key))}><span>{bin.when}</span><span>{bin.value}</span></button>)}</div></details>}{chart.missing && <div class="no-price">{screenText(chart.missing)}</div>}</>}</section>)}
    <div class="analytics-breakdown"><div class="analytics-bd-head"><h2>Breakdown</h2><div class="panel-sub">Agent-hours and API-equivalent cost; bars follow the toggle</div></div><div class="analytics-bd-bar"><div class="analytics-measure" role="group" aria-label="Breakdown bar measure">{[['hours', 'Agent-hours'], ['cost', 'API-equivalent cost']].map(([key, label]) => <button key={key} type="button" data-measure={key} aria-pressed={snapshot.measure === key} onClick={() => active(() => host.measure(key))}>{label}</button>)}</div></div><div class="analytics-breakdowns">{snapshot.breakdowns.map(group => <section key={group.key} class="analytics-panel"><h3>{group.heading}</h3><div class="analytics-list">{group.rows.map(row => <button key={row.key} class="analytics-row" type="button" data-breakdown={group.key} data-key={row.key} onClick={() => active(() => host.breakdown(group.key, row.key))}><span class="row-title">{screenText(row.name)}</span><span class="row-count">{row.count}</span><span class="row-track"><i class={'row-bar ' + width(row.width) + (row.color ? ' bar-' + row.color : '')} /></span><span class={'row-hours' + (snapshot.measure === 'hours' ? ' on' : '')}>{row.hours}</span><span class={'row-cost' + (snapshot.measure === 'cost' ? ' on' : '')}>{row.cost}</span>{row.missing && <span class="no-price">{screenText(row.missing)}</span>}</button>)}{!group.rows.length && <p class="empty">No activity in this range.</p>}</div></section>)}</div></div>
    <div class="analytics-split">{snapshot.lists.map(list => <section key={list.heading} class="analytics-panel"><h2>{screenText(list.heading)}</h2><div class="analytics-list">{list.rows.map(row => <Row key={row.id} row={row} widthClass={width(row.rank ?? 0)} open={() => active(() => host.session(row.id))} />)}{!list.rows.length && <p class="empty">No sessions in this range.</p>}</div></section>)}</div>
    {snapshot.models && <section class="analytics-panel models-panel"><h2>Models</h2><p class="panel-sub">Your launched work, compared within each difficulty band. Every measure shows its own sample count; unknown values are not estimated.</p>{!snapshot.models.length && <p class="empty">No launched work with recorded per-message models in this range.</p>}{snapshot.models.map(band => <><h3 key={'heading' + band.key}>{band.heading}</h3><div key={'table' + band.key} class="model-table-scroll" tabIndex={0} role="region" aria-label={band.key + ' model comparison'}><table class="model-table"><thead><tr>{snapshot.modelHeaders.map(heading => <th key={heading} scope="col">{screenText(heading)}</th>)}</tr></thead><tbody>{band.rows.map(row => <tr key={row.key}><td><button class="model-comparison-open" type="button" data-tip={row.tip} onClick={() => active(() => host.model(row.key))}>{screenText(row.name)}</button></td><td>{screenText(row.count)}</td>{row.cells.map((cell, i) => <td key={i} data-tip={cell.tip}><span>{cell.text}</span><span class="model-n">{'n=' + cell.n}</span></td>)}</tr>)}</tbody></table></div>{band.points.length ? <div key={'plot' + band.key} class="analytics-chart"><svg viewBox={'0 0 ' + band.width + ' 190'} role="img" aria-label={'API cost against first-pass acceptance for ' + band.key + ' work'}><line x1={42} x2={band.width - 12} y1={150} y2={150} class="gridline" /><line x1={42} x2={42} y1={12} y2={150} class="gridline" />{band.points.map((point, i) => <><circle key={'point' + i} cx={point.x} cy={point.y} r={5} class="model-point" data-tip={point.tip} aria-label={point.tip} /><text key={'point-label' + i} x={Math.max(42, Math.min(band.width - 90, point.x + 8))} y={Math.max(20, point.y - 8)} class="axis-label">{point.label}</text></>)}<text x={42} y={178} class="axis-label">Median API cost →</text><text x={2} y={16} class="axis-label">100%</text><text x={8} y={151} class="axis-label">0%</text></svg></div> : <p key={'empty' + band.key} class="panel-sub">Cost / acceptance plot needs both recorded measures.</p>}</>)}</section>}
    {snapshot.allowance && <section class="analytics-panel"><h2>Codex allowance</h2><div class="panel-sub">{screenText('Latest recorded rate limits · ' + snapshot.allowance.when)}</div><div class="allowance-grid">{snapshot.allowance.windows.map(window => <div key={window.label} class="allowance-window"><div class="window-name">{window.label}</div><div class="window-used">{window.used}</div><div class="window-reset">{window.reset}</div></div>)}</div></section>}
  </>}</>, root);
  host.committed();
}

export function renderSliceBody(root: HTMLElement, rows: readonly AnalyticsRow[], more: number, empty: string, open: (id: string) => void) {
  render(<>{!rows.length ? <p class="empty">{empty}</p> : <div class="analytics-list">{rows.map(row => <Row key={row.id} row={row} widthClass="" open={() => { if (root.isConnected) open(row.id); }} />)}{more > 0 && <p class="empty">{'and ' + more + ' more'}</p>}</div>}</>, root);
}
export interface ModelItem { id: string; name?: string; description: string; trace?: string; url?: string }
export function renderModelItems(root: HTMLElement, count: string, items: readonly ModelItem[], more: string | undefined, host: { session(id: string): void; trace(id: string): void }) {
  render(<><p class="panel-sub">{screenText(count)}</p>{items.map((item, i) => <div key={i} class="model-item">{item.name ? <button class="model-item-session" type="button" onClick={event => { if (event.currentTarget.isConnected) host.session(item.id); }}>{screenText(item.name)}</button> : <span>{screenText(item.id + ' · outside the session window')}</span>}<span class="panel-sub">{screenText(item.description)}</span>{item.trace && <button class="model-item-trace" type="button" onClick={event => { if (event.currentTarget.isConnected) host.trace(item.trace!); }}>Trace</button>}{item.url && <a href={item.url} target="_blank" rel="noopener noreferrer">Open pull request</a>}</div>)}{more && <p class="panel-sub">{more}</p>}</>, root);
}
