import { build, transform } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import ts from 'typescript';
import { gzipSync } from 'node:zlib';
import { checkSource, checkSources } from './security-check.mjs';
const dir = fileURLToPath(new URL('.', import.meta.url));
const license = readFileSync(new URL('./PREACT-LICENSE', import.meta.url), 'utf8').trim();
const output = '../crates/semon-sessions/src/viewer.generated.js';
export const buildViewer = (minify = false, entryPoints = ['src/viewer.ts'], includePreactLicense = true) => build({
  absWorkingDir: dir, entryPoints, bundle: true, write: false, format: 'iife',
  platform: 'browser', target: 'es2022', tsconfig: 'tsconfig.json', minify, metafile: true,
  define: { 'process.env.NODE_ENV': '"production"' }, legalComments: 'inline',
  banner: { js: '// Generated by ui/build.mjs; edit sources and run npm --prefix ui run build.' + (includePreactLicense ? `\n/*! Preact 10.29.8\n${license}\n*/` : '') },
});
export async function assertFresh(bytes, url) {
  if (!Buffer.from(bytes).equals(await readFile(url))) throw new Error('Stale viewer.generated.js: run npm --prefix ui run build');
}
/** Consumers use this pinned compiler/bundler and the library's sole Preact installation. */
export async function buildConsumer(entry, outputPath, check = false) {
  const entryPath = resolve(entry), destination = resolve(outputPath);
  if (!/\.tsx?$/.test(entryPath) || entryPath === destination) throw new Error('Consumer requires a typed entry and separate output');
  await checkSources();
  const config = ts.readConfigFile(resolve(dir, 'tsconfig.lib.json'), ts.sys.readFile);
  const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, dir);
  const program = ts.createProgram([entryPath], { ...parsed.options, allowImportingTsExtensions: true, paths: { 'preact': [resolve(dir, 'node_modules/preact')], 'preact/*': [resolve(dir, 'node_modules/preact/*')] } });
  const errors = ts.getPreEmitDiagnostics(program);
  if (errors.length) throw new Error(ts.formatDiagnosticsWithColorAndContext(errors, { getCanonicalFileName: name => name, getCurrentDirectory: () => dir, getNewLine: () => '\n' }));
  const result = await build({
    absWorkingDir: dir, entryPoints: [entryPath], bundle: true, write: false, format: 'iife',
    platform: 'browser', target: 'es2022', tsconfig: 'tsconfig.json', metafile: true,
    alias: { preact: resolve(dir, 'node_modules/preact') },
    define: { 'process.env.NODE_ENV': '"production"' }, legalComments: 'inline',
    banner: { js: `// Generated by Semon ui/build.mjs --entry; edit the typed source.\n/*! Preact 10.29.8\n${license}\n*/` },
  });
  for (const input of Object.keys(result.metafile.inputs)) {
    if (!input.includes('node_modules/') && /\.tsx?$/.test(input)) checkSource(await readFile(resolve(dir, input), 'utf8'), input);
  }
  const runtimes = Object.keys(result.metafile.inputs).filter(input => /preact\/dist\/preact\.module\.js$/.test(input));
  if (runtimes.length !== 1) throw new Error('Consumer must contain exactly one Preact runtime');
  const bytes = result.outputFiles[0].contents;
  if (check) { if (!Buffer.from(bytes).equals(await readFile(destination))) throw new Error('Stale consumer output: rebuild with the pinned Semon toolchain'); }
  else await writeFile(destination, bytes);
  return result;
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const entryIndex = process.argv.indexOf('--entry'), outputIndex = process.argv.indexOf('--output');
  if (entryIndex !== -1 || outputIndex !== -1) {
    if (!process.argv[entryIndex + 1] || entryIndex === -1 || !process.argv[outputIndex + 1] || outputIndex === -1) throw new Error('--entry and --output are required together');
    await buildConsumer(process.argv[entryIndex + 1], process.argv[outputIndex + 1], process.argv.includes('--check'));
    console.log(process.argv.includes('--check') ? 'Consumer asset is fresh' : 'Consumer asset built');
  } else {
  await checkSources();
  const result = await buildViewer();
  const bytes = result.outputFiles[0].contents;
  const url = new URL(output, import.meta.url);
  if (process.argv.includes('--check')) {
    await assertFresh(bytes, url);
    console.log('viewer.generated.js is fresh');
  } else if (!process.argv.includes('--sizes')) await writeFile(url, bytes);
  if (process.argv.includes('--sizes')) {
    const prefix = (await Promise.all(['tooltip.js', 'select.js'].map(name => readFile(new URL('../crates/semon-sessions/src/' + name, import.meta.url), 'utf8')))).join('\n') + '\n';
    const report = async (name, tail) => {
      const served = Buffer.concat([Buffer.from(prefix), Buffer.from(tail)]);
      const min = Buffer.from((await transform(served.toString(), { minify: true, target: 'es2022', legalComments: 'inline' })).code);
      console.log(`${name}: served raw ${served.length}, raw gzip-9 ${gzipSync(served, { level: 9 }).length}, minified ${min.length}, minified gzip-9 ${gzipSync(min, { level: 9 }).length} bytes`);
    };
    await report('production', bytes);
    const baselineArg = process.argv.indexOf('--baseline');
    if (baselineArg !== -1) {
      const path = process.argv[baselineArg + 1];
      if (!path) throw new Error('--baseline needs an absolute viewer.js path');
      const baseline = await buildViewer(false, [path], false);
      await report('baseline equivalent esbuild', baseline.outputFiles[0].contents);
      await report('baseline original served', await readFile(path));
    }
    console.log(JSON.stringify(result.metafile.outputs, null, 2));
  }
  }
}
