import { build, transform } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';
import { checkSources } from './security-check.mjs';
const dir = fileURLToPath(new URL('.', import.meta.url));
const license = readFileSync(new URL('./PREACT-LICENSE', import.meta.url), 'utf8').trim();
const output = '../crates/semon-sessions/src/viewer.generated.js';
export const buildViewer = (minify = false, entryPoints = ['src/viewer.ts'], includePreactLicense = true) => build({
  absWorkingDir: dir, entryPoints, bundle: true, write: false, format: 'iife',
  platform: 'browser', target: 'es2022', tsconfig: 'tsconfig.json', minify, metafile: true,
  define: { 'process.env.NODE_ENV': '"production"' }, legalComments: 'inline',
  banner: { js: '// Generated by ui/build.mjs; edit sources and run npm --prefix ui run build.' + (includePreactLicense ? `\n/*! Preact 10.29.8\n${license}\n*/` : '') },
});
export async function assertFresh(bytes, url) {
  if (!Buffer.from(bytes).equals(await readFile(url))) throw new Error('Stale viewer.generated.js: run npm --prefix ui run build');
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await checkSources();
  const result = await buildViewer();
  const bytes = result.outputFiles[0].contents;
  const url = new URL(output, import.meta.url);
  if (process.argv.includes('--check')) {
    await assertFresh(bytes, url);
    console.log('viewer.generated.js is fresh');
  } else if (!process.argv.includes('--sizes')) await writeFile(url, bytes);
  if (process.argv.includes('--sizes')) {
    const prefix = (await Promise.all(['tooltip.js', 'select.js'].map(name => readFile(new URL('../crates/semon-sessions/src/' + name, import.meta.url), 'utf8')))).join('\n') + '\n';
    const report = async (name, tail) => {
      const served = Buffer.concat([Buffer.from(prefix), Buffer.from(tail)]);
      const min = Buffer.from((await transform(served.toString(), { minify: true, target: 'es2022', legalComments: 'inline' })).code);
      console.log(`${name}: served raw ${served.length}, raw gzip-9 ${gzipSync(served, { level: 9 }).length}, minified ${min.length}, minified gzip-9 ${gzipSync(min, { level: 9 }).length} bytes`);
    };
    await report('production', bytes);
    const baselineArg = process.argv.indexOf('--baseline');
    if (baselineArg !== -1) {
      const path = process.argv[baselineArg + 1];
      if (!path) throw new Error('--baseline needs an absolute viewer.js path');
      const baseline = await buildViewer(false, [path], false);
      await report('baseline equivalent esbuild', baseline.outputFiles[0].contents);
      await report('baseline original served', await readFile(path));
    }
    console.log(JSON.stringify(result.metafile.outputs, null, 2));
  }
}
